# Generated by Django 2.1.3 on 2019-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
