# Generated by Django 2.1.1 on 2018-12-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('resident', 'resident'), ('mentor', 'mentor'), ('owner', 'owner')], max_length=15)),
                ('birth_date', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('specialization', models.CharField(choices=[('Software Developer', 'Software Developer'), ('Designer', 'Designer'), ('Front End', 'Front End'), ('Back End', 'Back End'), ('Other', 'Other')], max_length=30)),
                ('team', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photos')),
            ],
        ),
    ]
