# Generated by Django 2.1.2 on 2018-11-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='last_entry',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='photo_4',
        ),
    ]
