# Generated by Django 2.1.2 on 2018-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_mentor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='photo_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
