# Generated by Django 2.1.2 on 2018-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_resident_photo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='photo_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo_5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
