# Generated by Django 2.1.2 on 2018-12-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20181204_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('resident', 'resident'), ('mentor', 'mentor'), ('owner', 'owner')], default=None, max_length=15)),
                ('photo_1', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_2', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_3', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_4', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_5', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
