# Generated by Django 2.1.2 on 2018-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
