# Generated by Django 2.1.2 on 2018-12-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_user_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
    ]
